# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
[window]


padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"
option_as_alt = "Both"
[font]

normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size = 14.0


[cursor]

style.shape = "Block"

vi_mode_style = "Beam"
